### ISSUE TITLE
Make @india a collective initiative

### ISSUE THREAD

**Issue by planemad** [india/handyman#1]
@mohnish thank you for reserving the @india org name. Looks like it can serve as a collective homepage for various open initiatives similar to https://github.com/unitedstates

If you can add me as a member, i'm happy to do some initial work to organise.

**Comment by mohnish** [comment]
Hi @planemad, thanks for reaching out. At this point, I have other ideas with the organization. I will publish them at a later point. Appreciate the interest though.
